// <auto-generated />
namespace GardenManager.Web.DataContexts.GardenMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MinorTableChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MinorTableChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201412122026460_MinorTableChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
